apiVersion: v1
kind: Service
metadata:
  name: matchmaker
  labels:
    app: matchmaker
spec:
  ports:
  - port: 90
    targetPort: 90
    name: port90
  - port: 9999
    targetPort: 9999
    name: port9999
  selector:
    app: matchmaker 
  type: LoadBalancer

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
  labels:
    app: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
    spec:
      containers:
      - name: matchmaker
        image: fancy.azurecr.io/matchmaker:4.27
        ports:
        - containerPort: 90
        - containerPort: 9999
        volumeMounts:
        - name: pixel-streaming-config
          mountPath: /config
      volumes:
        - name: pixel-streaming-config
          configMap:
            name: pixel-streaming-config 
