apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: GAME
  newName: albistest1container.azurecr.io/game
  newTag: "4.28"
- name: KUBECTL
  newName: bitnami/kubectl
  newTag: "latest"
- name: MATCHMAKER
  newName: hassamdevops/turn
  newTag: "matchmaker"
- name: REDIS
  newName: bitnami/redis
  newTag: "latest"
- name: TURN
  newName: hassamdevops/turn
  newTag: "signalwebserver"
- name: SCALEMONITOR
  newName: hassamdevops/turn
  newTag: "scalmonitor1"
- name: SIGNALLINGWEBSERVER
  newName: hassamdevops/turn
  newTag: "signalwebserver"
