apiVersion: apps/v1
kind: Deployment
metadata:
  name: signallingserver
spec:
  template:
    spec:
      initContainers:
      - name: init
        image:     
      containers:
      - name: signallingserver
        image: 